### PR TITLE
Fix the build system

### PR DESCRIPTION
**Pull request by samoht**
All the modules should be declared in an _oasis library

### CODE REVIEW

**Comment by samoht** [comment]
After this changes, `#require "profuse"` works in a toplevel.

**Comment by samoht** [comment]
I have also added a Travis file, @dsheets can you enable the tests for this repository?

**Comment by dsheets** [comment]
Enabled. Testing your build system regen now.

**Comment by dsheets** [comment]
Thanks!

**Comment by dsheets** [comment]
Hmm... still get:

```
# #require "profuse";;
Error: Reference to undefined global `Fd_send_recv'
```

**Pull request merged**
