### PR TITLE
Try to fix Travis

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
Right, not sure that the tests are supposed to run fine in Travis:

```
 fusermount: failed to unmount /home/travis/.opam/system/build/my-package.~unknown/linux_test/mnt: Invalid argument
- fusermount: failed to unmount /home/travis/.opam/system/build/my-package.~unknown/linux_test/multi: Invalid argument
```

**Comment by dsheets** [comment]
Travis doesn't support FUSE.

**Comment by samoht** [comment]
ok, Travis works for 4.01 but fails with a random error on 4.02. Any idea why? It's maybe related to ctypes?

```
#=== ERROR while installing unix-dirent.0.1.0 =================================#
# opam-version 1.2.2
# os           linux
# command      make build
# path         /home/travis/.opam/system/build/unix-dirent.0.1.0
# compiler     system (4.02.1)
# exit-code    2
# env-file     /home/travis/.opam/system/build/unix-dirent.0.1.0/unix-dirent-9052-e1320e.env
# stdout-file  /home/travis/.opam/system/build/unix-dirent.0.1.0/unix-dirent-9052-e1320e.out
# stderr-file  /home/travis/.opam/system/build/unix-dirent.0.1.0/unix-dirent-9052-e1320e.err
### stdout ###
# ocamlfind ocamlc -o _build/lib/unix_dirent_private.cmi \
# [...]
# ocamlfind ocamlc -o _build/lib/unix_dirent_common.cmi \
#       -syntax camlp4o -package ctypes.foreign -package sexplib.syntax -package comparelib.syntax -package bin_prot.syntax -c lib/unix_dirent_common.mli
# ocamlfind ocamlc -o _build/lib/unix_dirent.cmi -I _build/lib -I lib \
#       -syntax camlp4o -package ctypes.foreign -package sexplib.syntax -package comparelib.syntax -package bin_prot.syntax -c lib/unix/unix_dirent.mli
# ocamlfind ocamlmklib -o _build/lib/unix_dirent -I _build/lib \
#       -ocamlc   "ocamlfind ocamlc -syntax camlp4o -package ctypes.foreign -package sexplib.syntax -package comparelib.syntax -package bin_prot.syntax" \
#       -ocamlopt "ocamlfind ocamlopt -syntax camlp4o -package ctypes.foreign -package sexplib.syntax -package comparelib.syntax -package bin_prot.syntax" \
#       -package ctypes.foreign -package sexplib.syntax -package comparelib.syntax -package bin_prot.syntax lib/unix_dirent_private.ml lib/unix_dirent_common.ml \
#       lib/unix/unix_dirent.ml _build/lib/unix/unix_dirent_stubs.o
### stderr ###
# >> Fatal error: Selection.emit_expr: unbound var addr_1353
# Fatal error: exception Misc.Fatal_error
# make: *** [build] Error 2
```

**Comment by dsheets** [comment]
Looks like it's due to http://caml.inria.fr/mantis/view.php?id=6686 which means the problem is with code gen on 4.02.1. I'd rather blacklist 4.02.1 than attempt workaround.

**Pull request closed without merging**
